name: Maven Build, SonarQube and Nexus

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # Checkout Source Code
      - name: Checkout Source
        uses: actions/checkout@v4

      # Java 8 for Maven Build
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      # Build Application
      - name: Build Project
        run: mvn clean install -DskipTests

      # Verify WAR File
      - name: Verify WAR File
        run: |
          ls -lh target

      # Java 17 for SonarQube
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=petclinic \
            -Dsonar.projectName=petclinic \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN

      # Upload WAR to Nexus
      - name: Upload Artifact to Nexus
        run: |
          FILE=$(find target -name "*.war" | head -1)

          echo "Uploading: $FILE"

          curl -v \
            -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" \
            --upload-file "$FILE" \
            "http://52.197.210.82:8081/repository/maven-snapshots/$(basename "$FILE")"
